# $NetBSD: $
#

COMMENT=	Minix specific packages

# The following needs to be re-imported and fixed.
# For current state, please see branch 3.3.0-dev
#SUBDIR+=	dde-linux26
#SUBDIR+=	dde-linux26-usb-drivers
SUBDIR+=	git-review
#SUBDIR+=	netdrv_tg3
#SUBDIR+=	stp

.include "../mk/misc/category.mk"
