#!/bin/sh
#
# $NetBSD: INSTALL,v 1.3 2006/06/15 20:40:15 jlam Exp $

ADOBE_RESOURCEDIR="@ADOBE_RESOURCEDIR@"
GS_RESOURCEDIR="@GS_RESOURCEDIR@"
PKG_INFO="@PKG_INFO@"

case ${STAGE} in
POST-INSTALL)
	${PKG_INFO} -qL adobe-cmaps | ${GREP} "/Resource/CMap/" |
	while read src; do
		base=`${BASENAME} $src`
		dest="${GS_RESOURCEDIR}/CMap/$base"
		${RM} -f $dest
		${LN} -sf $src $dest
	done
	;;
esac
